# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Daycare Parent' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Daycare Parent
  pod 'Material’
  pod 'IQKeyboardManagerSwift'
  pod 'OpalImagePicker'
  pod 'SDWebImage'
  pod 'SpinKit'
  pod 'ActionSheetPicker-3.0'
  pod 'DropDown'
  pod 'Stripe'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'TKImageShowing'
  pod 'FSCalendar'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'SwiftSignalRClient'
  target 'Daycare ParentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Daycare ParentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
