# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Daycare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Daycare
 pod 'Material’
  pod 'IQKeyboardManagerSjwift'
  pod 'DropDown'
  pod 'ActionSheetPicker-3.0'
  pod 'SDWebImage'
  pod 'VACalendar'
  pod 'OpalImagePicker'
  pod 'Floaty'
  pod 'SpinKit'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'TKImageShowing'
  pod 'FSCalendar'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'SwiftSignalRClient'
 
end
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end



